name: book_store
description: AppAvengers Assignment Project


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  fluttertoast: ^8.0.8
  provider: ^6.0.2
  intl: ^0.17.0
  flutter_lints: ^1.0.0
  http: ^0.13.4
  fluttericon: ^2.0.0

flutter:

  uses-material-design: true

